---
abstract: "Simple set-and-forget using of a '/share' directory in your projects root"
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Class::Tiny: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  FindBin: '0'
  Test::More: '0.96'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.034, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-ShareDir-ProjectDistDir
provides:
  File::ShareDir::ProjectDistDir:
    file: lib/File/ShareDir/ProjectDistDir.pm
    version: '1.000008'
recommends:
  Path::Tiny: '0.058'
requires:
  Carp: '0'
  File::ShareDir: '0'
  Path::FindDev: '0'
  Path::IsDev: '0'
  Path::Tiny: '0'
  Sub::Exporter: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/File-ShareDir-ProjectDistDir/issues
  homepage: https://github.com/kentnl/File-ShareDir-ProjectDistDir
  repository: https://github.com/kentnl/File-ShareDir-ProjectDistDir.git
version: '1.000008'
x_BuiltWith:
  external_file: misc/built_with.json
x_Dist_Zilla:
  perl:
    version: '5.021009'
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::KENTNL/MetaConfig'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::KENTNL/GithubMeta'
      version: '0.48'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '5.034'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@Author::KENTNL/MetaProvides::Package'
      version: '2.003001'
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          external_file_name: misc/built_with.json
          show_config: '1'
          show_uname: '1'
          uname:
            uname_args:
              - -s
              - -o
              - -r
              - -m
              - -i
            uname_call: uname
          use_external_file: only
      name: '@Author::KENTNL/MetaData::BuiltWith'
      version: '1.004002'
    -
      class: Dist::Zilla::Plugin::Git::Contributors
      config:
        Dist::Zilla::Plugin::Git::Contributors:
          include_authors: '0'
          include_releaser: '0'
          order_by: name
          paths: []
      name: '@Author::KENTNL/Git::Contributors'
      version: '0.011'
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename:
            - README
            - README.mkdn
            - README.pod
            - LICENSE
          exclude_match: []
          follow_symlinks: '0'
          include_dotfiles: '1'
          prefix: ''
          prune_directory: []
          root: .
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: '0'
      name: '@Author::KENTNL/Git::GatherDir'
      version: '2.033'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::KENTNL/License'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::KENTNL/MetaJSON'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::KENTNL/MetaYAML'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::KENTNL/Manifest'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::Author::KENTNL::TravisCI
      name: '@Author::KENTNL/Author::KENTNL::TravisCI'
      version: '0.001002'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Author::KENTNL/CopyXBuild'
      version: '0.150250'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::KENTNL/MetaTests'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::KENTNL/PodCoverageTests'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::KENTNL/PodSyntaxTests'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Author::KENTNL/Test::ReportPrereqs'
      version: '0.021'
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      config:
        Dist::Zilla::Plugin::Test::Kwalitee:
          filename: xt/release/kwalitee.t
          skiptest: []
      name: '@Author::KENTNL/Test::Kwalitee'
      version: '2.11'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/author/eol.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
          trailing_whitespace: '1'
      name: '@Author::KENTNL/Test::EOL'
      version: '0.17'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::KENTNL/Test::MinimumVersion'
      version: '2.000006'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/Test::Compile::PerFile/AUTOVIV/:InstallModulesPM'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::Test::Compile::PerFile
      config:
        Dist::Zilla::Plugin::Test::Compile::PerFile:
          file:
            - lib/File/ShareDir/ProjectDistDir.pm
          path_translator: base64_filter
          prefix: t/00-compile
          skip: []
          test_template: 01-basic.t.tpl
          xt_mode: ~
      name: '@Author::KENTNL/Test::Compile::PerFile'
      version: '0.003000'
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::KENTNL/Test::Perl::Critic'
      version: '3.000'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::KENTNL/ManifestSkip'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::RewriteVersion::Sanitized
      config:
        Dist::Zilla::Role::Version::Sanitize:
          mantissa: '6'
          normal_form: numify
      name: '@Author::KENTNL/RewriteVersion::Sanitized'
      version: '0.001005'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.011'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.011'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: -SingleEncoding
              version: '4.011'
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: '4.011'
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: '4.011'
            -
              class: Pod::Weaver::Section::Generic
              name: DETERRENT
              version: '4.011'
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: '4.011'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.011'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.011'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.011'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.011'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.011'
            -
              class: Pod::Weaver::Section::Collect
              name: PRIVATE_ATTRIBUTES
              version: '4.011'
            -
              class: Pod::Weaver::Section::Collect
              name: PRIVATE_METHODS
              version: '4.011'
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: '4.011'
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: '4.011'
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: '4.011'
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: '4.011'
      name: '@Author::KENTNL/PodWeaver'
      version: '4.006'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::KENTNL/AutoPrereqs'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: suggests
      name: '@Author::KENTNL/BundleDevelSuggests'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::Prereqs::AuthorDeps
      name: '@Author::KENTNL/Prereqs::AuthorDeps'
      version: '0.004'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::KENTNL/MinimumPerl'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::KENTNL/Authority'
      version: '1.009'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: '10'
      name: '@Author::KENTNL/MakeMaker'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::Author::KENTNL::RecommendFixes
      name: '@Author::KENTNL/Author::KENTNL::RecommendFixes'
      version: '0.004002'
    -
      class: Dist::Zilla::Plugin::Readme::Brief
      name: '@Author::KENTNL/ShippedReadme'
      version: '0.002005'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::KENTNL/ReadmeAnyFromPod'
      version: '0.150250'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::KENTNL/Test::CPAN::Changes'
      version: '0.009'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: '10'
      name: '@Author::KENTNL/RunExtraTests'
      version: '0.026'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::KENTNL/TestRelease'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::KENTNL/ConfirmRelease'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/Git::Check'
      version: '2.033'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/commit_dirty_files'
      version: '2.033'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: 1.000008-source
          tag_format: '%v-source'
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/tag_master'
      version: '2.033'
    -
      class: Dist::Zilla::Plugin::Git::NextRelease
      name: '@Author::KENTNL/Git::NextRelease'
      version: '0.004000'
    -
      class: Dist::Zilla::Plugin::BumpVersionAfterRelease
      name: '@Author::KENTNL/BumpVersionAfterRelease'
      version: '0.009'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match:
            - (?^u:^lib/)
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/commit_release_changes'
      version: '2.033'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: builds
          build_root: ~
          message: 'Build results of %h (on %b)'
          multiple_inheritance: 0
          release_branch: releases
          release_message: 'Build results of %h (on %b)'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/Git::CommitBuild'
      version: '2.033'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: releases
          signed: 0
          tag: '1.000008'
          tag_format: '%v'
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/tag_release'
      version: '2.033'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::KENTNL/UploadToCPAN'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@Author::KENTNL/Twitter'
      version: '0.026'
    -
      class: Dist::Zilla::Plugin::Prereqs::Upgrade
      config:
        Dist::Zilla::Plugin::Prereqs::Upgrade:
          modules:
            Dist::Zila::Plugin::MetaProvides::Package: '2.000000'
            Dist::Zilla: '5'
            ExtUtils::MakeMaker: '7.00'
            File::ShareDir::Install: '0.10'
            Moo: '1.000008'
            Moose: '2.000'
            Path::Tiny: '0.058'
            Test::File::ShareDir: '1.000000'
            Test::More: '0.99'
      name: '@Author::KENTNL/Prereqs::Upgrade'
      version: '0.001000'
    -
      class: Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled
      config:
        Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled:
          applyto_map:
            - 'develop.suggests = develop.suggests'
          applyto_phase:
            - develop
          modules:
            - Dist::Zilla::PluginBundle::Author::KENTNL
            - Dist::Zilla::App::Command::bakeini
          source_relation: requires
          target_relation: recommends
      name: '@Author::KENTNL/always_latest_develop_bundle'
      version: '0.003001'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/::Role::BundleDeps'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '5.034'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.034'
x_authority: cpan:KENTNL
x_contributors:
  - 'Michael Jemmeson <mjemmeson@cpan.org>'
  - 'Michał Wojciechowski <odyniec@odyniec.eu.org>'
